### ISSUE TITLE
Not on Hackage!

### ISSUE THREAD

**Issue by deepfire** [athanclark/cassowary-haskell#2]
This package seems like it could be useful to the wider auditory of Hackage users.. : -)

**Comment by athanclark** [comment]
Well, my issue with it is that it's not a correct implementation. I'm not exactly how to prove that degenerecy is avoided with Bland's rule; in a different implementation I made, I couldn't prevent cycling. So I will definitely not publish this until I think it's correct :\ Thank you for the lookout though!
